spring:
  application:
    name: config-client   # same name used in config server
  config:
    import: configserver:http://config-server:8888


server:
  port: 8081
logging:
  level:
    com.wknd.spring.client.config_client: DEBUG
